apiVersion: v1
kind: Service
metadata:
  name: javawebapp-service
spec:
  selector:
    app: my-nginx
    version: v2
    color: green
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 32654